#include <zapup/shims.h>

bool z_sh_generate_shim_for(ZPathView self, ZapToolchainElement tool, ZStringBuf* out) {
    ZStringView tool_string = z_format_zap_toolchain_element(tool);

    if (!z_strbuf_appendf(out, "#!/bin/sh\n")) return false;
    if (!z_strbuf_appendf(out, "# NOTE: This file is auto-generated by zapup and should not be modified directly\n")) return false;
    if (!z_strbuf_appendf(out, "BIN=\"$(\"" Z_SV_FMT "\" which \"" Z_SV_FMT "\")\"", Z_SV_FARG(self), Z_SV_FARG(tool_string))) return false;
    if (!z_strbuf_appendf(out, " || exit $?\n")) return false;
    if (!z_strbuf_appendf(out, "exec \"$BIN\"")) return false;

    return true;
}

bool z_batch_generate_shim_for(ZPathView self, ZapToolchainElement tool, ZStringBuf* out) {
    (void) self, (void) tool, (void) out;
    // TODO
    return false;
}

