#include <zapup/shims.h>

bool z_generate_sh_shim_for(ZPathView self, ZapToolchainElement tool, ZStringBuf* out) {
    ZStringView tool_string = z_format_zap_toolchain_element(tool);

    if (!z_strbuf_appendf(out, "#!/bin/sh\n")) return false;
    if (!z_strbuf_appendf(out, "# NOTE: This file is auto-generated by zapup and should not be modified directly\n")) return false;
    if (!z_strbuf_appendf(out, "BIN=\"$(\"" Z_SV_FMT "\" which \"" Z_SV_FMT "\")\"", Z_SV_FARG(self), Z_SV_FARG(tool_string))) return false;
    if (!z_strbuf_appendf(out, " || exit $?\n")) return false;
    if (!z_strbuf_appendf(out, "exec \"$BIN\" \"$@\"")) return false;

    return true;
}

bool z_generate_batch_shim_for(ZPathView self, ZapToolchainElement tool, ZStringBuf* out) {
    (void) self, (void) tool, (void) out;
    // TODO
    return false;
}

bool z_generate_native_shim_for(ZPathView self, ZapToolchainElement tool, ZStringBuf* out) {
#if Z_PLATFORM_IS_WINDOWS
    return z_generate_batch_shim_for(self, tool, out);
#elif Z_PLATFORM_IS_POSIX
    return z_generate_sh_shim_for(self, tool, out);
#else
    (void) self, (void) tool, (void) out;
    return false;
#endif
}
